### ISSUE TITLE
Images are public

### ISSUE THREAD

**Issue by kishorebolt03** [0xdedinfosec/0xdedinfosec.github.io#1] opened 2021-05-25 03:01 UTC
All the HTB machine images are public
Even if you hide the pages with root hash i can see the images from this repository

**Comment by 0xdedinfosec** [comment] 2021-05-25 03:29
working on that bro thinking how to fix that if you have any idea tell me

**Comment by 0xdedinfosec** [comment] 2021-06-02 03:24
Now the issue is fixed in the writeup spider

**Closed as completed** 2021-06-02 03:24 UTC

**Comment by kishorebolt03** [comment] 2021-06-03 03:36
Nice 👍👍👍
